#!/usr/bin/env bash
# Regenerates the two paste-able SQL bundles from supabase/migrations/*.sql. Run from the supabase folder:  bash regen.sh
cd "$(dirname "$0")"
{ echo "-- ALL MIGRATIONS in order, generated from supabase/migrations/*.sql. Paste into the Supabase SQL editor and run once."
  echo "-- Do not edit this file: change the individual migrations and run  bash regen.sh"
  for f in $(ls migrations/*.sql | sort); do echo; echo "-- ============================================================"; echo "-- $f"; echo "-- ============================================================"; cat "$f"; done; } > all-migrations.sql
# CATCH-UP: everything after the first nine migrations (the ones applied to the live project first), hardening last.
{ echo "-- CATCH-UP: every migration after the first nine, ending with the security hardening. Paste into the Supabase SQL editor and run ONCE."
  echo "-- If you already ran an earlier catch-up file, run only the migrations newer than the last one you ran, then migration 29991231000000_hardening.sql again."
  echo "-- Generated from supabase/migrations/*.sql: do not edit; run  bash regen.sh"
  for f in $(ls migrations/*.sql | sort | awk -F/ '$2 >= "20261006120900"'); do echo; echo "-- ============================================================"; echo "-- $f"; echo "-- ============================================================"; cat "$f"; done; } > catch-up-migrations.sql
echo "regenerated: $(ls migrations | wc -l) migrations"
