#!/usr/bin/env bash
# Regenerates the two paste-able SQL bundles from supabase/migrations/*.sql. Run from the supabase folder:  bash regen.sh
cd "$(dirname "$0")"
{ echo "-- ALL MIGRATIONS in order, generated from supabase/migrations/*.sql. Paste into the Supabase SQL editor and run once."
  echo "-- Do not edit this file: change the individual migrations and run  bash regen.sh"
  for f in $(ls migrations/*.sql | sort); do echo; echo "-- ============================================================"; echo "-- $f"; echo "-- ============================================================"; cat "$f"; done; } > all-migrations.sql
# CATCH-UP: everything after the first nine migrations (the ones applied to the live project first), hardening last.
{ echo "-- CATCH-UP: every migration after the first nine, ending with the security hardening. Paste into the Supabase SQL editor and run ONCE."
  echo "-- If you already ran an earlier catch-up file, run only the migrations newer than the last one you ran, then migration 29991231000000_hardening.sql again."
  echo "-- Generated from supabase/migrations/*.sql: do not edit; run  bash regen.sh"
  for f in $(ls migrations/*.sql | sort | awk -F/ '$2 >= "20261006120900"'); do echo; echo "-- ============================================================"; echo "-- $f"; echo "-- ============================================================"; cat "$f"; done; } > catch-up-migrations.sql
echo "regenerated: $(ls migrations | wc -l) migrations"
# CATCH-UP 2: only what came after the first catch-up file (attendance and later), hardening last. For a project that already ran catch-up-migrations.sql from before attendance existed.
{ echo "-- CATCH-UP 2: attendance and pickup (Prompt 12), daily reports (Prompt 13) and any later migrations, plus the security hardening. Paste into the Supabase SQL editor and run ONCE."
  echo "-- Only for a project that already ran an earlier catch-up-migrations.sql (one that did NOT include 20261006121500_attendance.sql)."
  echo "-- Generated from supabase/migrations/*.sql: do not edit; run  bash regen.sh"
  for f in $(ls migrations/*.sql | sort | awk -F/ '$2 >= "20261006121500"'); do echo; echo "-- ============================================================"; echo "-- $f"; echo "-- ============================================================"; cat "$f"; done; } > catch-up-2-attendance.sql
# CATCH-UP 3: only daily reports and later, hardening last. For a project that already ran catch-up 1 or 2 WITH attendance but before daily reports.
{ echo "-- CATCH-UP 3: daily reports (Prompt 13) and any later migrations, plus the security hardening. Paste into the Supabase SQL editor and run ONCE."
  echo "-- Only for a project that already ran an earlier catch-up that included 20261006121500_attendance.sql but NOT 20261006121600_daily_reports.sql."
  echo "-- Generated from supabase/migrations/*.sql: do not edit; run  bash regen.sh"
  for f in $(ls migrations/*.sql | sort | awk -F/ '$2 >= "20261006121600"'); do echo; echo "-- ============================================================"; echo "-- $f"; echo "-- ============================================================"; cat "$f"; done; } > catch-up-3-daily-reports.sql
# CATCH-UP 4: announcements and later (menu, events, photos, admin area), hardening last. For a project that already ran catch-up 3 (daily reports) but nothing newer.
{ echo "-- CATCH-UP 4: announcements, menu and events, photos and videos, the admin area, plus the security hardening. Paste into the Supabase SQL editor and run ONCE."
  echo "-- Only for a project that already ran an earlier catch-up that included 20261006121600_daily_reports.sql but NOT 20261006121700_announcements.sql."
  echo "-- Generated from supabase/migrations/*.sql: do not edit; run  bash regen.sh"
  for f in $(ls migrations/*.sql | sort | awk -F/ '$2 >= "20261006121700"'); do echo; echo "-- ============================================================"; echo "-- $f"; echo "-- ============================================================"; cat "$f"; done; } > catch-up-4-communication.sql
# CATCH-UP 5: absences and approvals, payments, birthdays and transport, hardening last. For a project that already ran catch-up 4 (up to the questions migration) but nothing newer.
{ echo "-- CATCH-UP 5: absence follow-up, approval reminders, payments, birthdays and transport, plus the security hardening. Paste into the Supabase SQL editor and run ONCE."
  echo "-- Only for a project that already ran an earlier catch-up that included 20261006122100_questions.sql but NOT 20261006122200_absences_approvals.sql."
  echo "-- Generated from supabase/migrations/*.sql: do not edit; run  bash regen.sh"
  for f in $(ls migrations/*.sql | sort | awk -F/ '$2 >= "20261006122200"'); do echo; echo "-- ============================================================"; echo "-- $f"; echo "-- ============================================================"; cat "$f"; done; } > catch-up-5-absences-payments.sql
