// Wording for the public registration form, English and Arabic (right-to-left).
// Arabic uses the neutral-masculine form common in app interfaces; please have a native speaker review it.
window.REG_STR = {
  en: {
    title: "Register your child", brand: "Cute Kids Academy",
    intro: "Welcome! This takes about 10 minutes. You do not need an account. You can stop at any time: your answers are saved on this device for 7 days.",
    saved: "Your answers are saved on this device only.", clear: "Clear my saved answers", cleared: "Your saved answers were cleared.",
    shared: "If this is a shared phone or computer, please clear your saved answers when you finish.",
    step: "Step", of: "of", back: "Back", next: "Next", submit: "Submit my application", sending: "Sending…", edit: "Edit",
    "s.1": "Your child", "s.2": "Parents", "s.3": "Health", "s.4": "Pickup", "s.5": "Consents", "s.6": "Documents", "s.7": "Review",
    required: "Please fill in the highlighted fields.", optional: "optional",
    child_name: "Child's full name", child_dob: "Date of birth", programme: "Programme", preferred_start: "Preferred start date", child_photo: "A photo of your child",
    "prog.nursery": "Nursery", "prog.preschool": "Preschool", "prog.after_school": "After-school", "prog.camp": "Camp", choose: "Choose…",
    parent_n: "Parent or guardian", full_name: "Full name", phone: "Phone number", email: "Email address", relationship: "Relationship to the child",
    "rel.mother": "Mother", "rel.father": "Father", "rel.guardian": "Guardian", "rel.other": "Other",
    add_parent: "Add a second parent or guardian", remove: "Remove", email_lang: "Language for our emails", "lang.en": "English", "lang.ar": "Arabic",
    email_hint: "We will send your confirmation here, and the portal invitation if your child is accepted.",
    health_intro: "This helps us keep your child safe. Only the academy's management and your child's own teachers see allergies. Write \"none\" if there is nothing to tell us.",
    allergies: "Allergies", medical_conditions: "Medical conditions", medications: "Medications", doctor_name: "Your child's doctor", doctor_phone: "Doctor's phone number",
    pickup_intro: "Who may collect your child? Please add every adult we may hand your child to (parents too). We will ask for ID at pickup. You can change this list later in the parent portal.",
    pickup_n: "Person", pickup_add: "Add another person", pickup_id: "A photo of their ID card", pickup_none: "No one added yet.",
    consent_intro: "Please answer yes or no to each one. You can change your mind at any time by telling the academy.",
    "c.photos_class": "Photos and videos of my child during class activities, shared only with our families",
    "c.photos_social": "Photos of my child on the academy's social media",
    "c.outings": "My child may go on outings and trips with the academy",
    "c.emergency_treatment": "The academy may arrange emergency medical treatment if it cannot reach me",
    "c.birthday_wall": "Show my child's first name, first initial and age on the birthday wall of the website",
    yes: "Yes", no: "No",
    docs_intro: "Please upload a clear photo or scan (JPG, PNG, WebP, HEIC or PDF, up to 5 MB each). You can also send them later: we will ask you if anything is missing.",
    doc_birth: "Birth certificate", doc_vacc: "Vaccination record", doc_other: "Another document (optional)", doc_add: "Add a file", uploading: "Uploading…", uploaded: "Uploaded", doc_remove: "Remove",
    upload_failed: "That file could not be uploaded. Please try again.", bad_type: "Please choose a photo (JPG, PNG, WebP, HEIC) or a PDF.", too_big: "That file is bigger than 5 MB. Please choose a smaller one.",
    rate: "That is a lot of files. Please try again in a little while.",
    review_intro: "Please check everything. You can go back to change an answer.", review_none: "None given",
    confirm: "I confirm that the information is correct, and I have read the", privacy: "privacy notice",
    need_confirm: "Please tick the box to confirm.",
    trap_label: "Leave this empty",
    done_title: "Thank you! We have received your application", done_no: "Your application number is", done_email: "We have sent a confirmation to",
    done_next: "What happens next: our team reviews your application and contacts you. If we need something more, or to arrange a tour, we will get in touch. If your child is accepted you will receive an email with a link to set up your parent portal login.",
    done_call: "Questions? Call us on 01063344389 (Sunday to Thursday, 8am to 6pm).", done_home: "Back to the website",
    err_generic: "Something went wrong. Please check your connection and try again.", err_dup: "We already have an application for this child from this email address. If you need to change something, please contact the academy.",
    err_rate: "We have received several applications from you already. Please try again later, or contact the academy.", err_fast: "Please take a moment to check your answers, then press submit again.", err_missing: "One of your uploaded files did not arrive. Please go back to the Documents step and upload it again.",
    off: "Online registration is not open yet. Please use the quick enquiry form on our website, or call 01063344389.", noscript: "Please turn on JavaScript to use the registration form.",
    bad_phone: "Please enter a valid phone number.", bad_email: "Please enter a valid email address.", bad_date: "Please check the date.",
  },
  ar: {
    title: "سجّل طفلك", brand: "كيوت كيدز أكاديمي",
    intro: "أهلاً بك! يستغرق هذا حوالي ١٠ دقائق. لا تحتاج إلى حساب. يمكنك التوقف في أي وقت: تُحفظ إجاباتك على هذا الجهاز لمدة ٧ أيام.",
    saved: "تُحفظ إجاباتك على هذا الجهاز فقط.", clear: "مسح إجاباتي المحفوظة", cleared: "تم مسح إجاباتك المحفوظة.",
    shared: "إذا كان هذا هاتفاً أو حاسوباً مشتركاً، يُرجى مسح إجاباتك المحفوظة عند الانتهاء.",
    step: "الخطوة", of: "من", back: "رجوع", next: "التالي", submit: "إرسال طلبي", sending: "جارٍ الإرسال…", edit: "تعديل",
    "s.1": "طفلك", "s.2": "أولياء الأمور", "s.3": "الصحة", "s.4": "الاستلام", "s.5": "الموافقات", "s.6": "المستندات", "s.7": "المراجعة",
    required: "يُرجى ملء الحقول المحددة.", optional: "اختياري",
    child_name: "الاسم الكامل للطفل", child_dob: "تاريخ الميلاد", programme: "البرنامج", preferred_start: "تاريخ البدء المفضل", child_photo: "صورة لطفلك",
    "prog.nursery": "الحضانة", "prog.preschool": "ما قبل المدرسة", "prog.after_school": "ما بعد المدرسة", "prog.camp": "المعسكر", choose: "اختر…",
    parent_n: "وليّ الأمر", full_name: "الاسم الكامل", phone: "رقم الهاتف", email: "البريد الإلكتروني", relationship: "صلة القرابة بالطفل",
    "rel.mother": "الأم", "rel.father": "الأب", "rel.guardian": "وصيّ", "rel.other": "أخرى",
    add_parent: "إضافة وليّ أمر ثانٍ", remove: "حذف", email_lang: "لغة رسائلنا", "lang.en": "الإنجليزية", "lang.ar": "العربية",
    email_hint: "سنرسل تأكيد الطلب إلى هنا، وكذلك دعوة بوابة أولياء الأمور إذا قُبل طفلك.",
    health_intro: "يساعدنا هذا في الحفاظ على سلامة طفلك. لا يرى الحساسية سوى إدارة الحضانة ومعلمي طفلك. اكتب «لا يوجد» إن لم يكن لديك ما تخبرنا به.",
    allergies: "الحساسية", medical_conditions: "الحالات الطبية", medications: "الأدوية", doctor_name: "طبيب طفلك", doctor_phone: "رقم هاتف الطبيب",
    pickup_intro: "من يحق له استلام طفلك؟ يُرجى إضافة كل شخص بالغ يمكننا تسليم طفلك له (بمن فيهم الوالدان). سنطلب إثبات الهوية عند الاستلام. يمكنك تعديل هذه القائمة لاحقاً من بوابة أولياء الأمور.",
    pickup_n: "الشخص", pickup_add: "إضافة شخص آخر", pickup_id: "صورة بطاقة هويته", pickup_none: "لم تتم إضافة أحد بعد.",
    consent_intro: "يُرجى الإجابة بنعم أو لا على كل بند. يمكنك تغيير رأيك في أي وقت بإخبار الحضانة.",
    "c.photos_class": "صور ومقاطع فيديو لطفلي أثناء أنشطة الفصل، تُشارك مع أسرنا فقط",
    "c.photos_social": "صور لطفلي على وسائل التواصل الاجتماعي الخاصة بالحضانة",
    "c.outings": "يمكن لطفلي المشاركة في الرحلات والخروجات مع الحضانة",
    "c.emergency_treatment": "يجوز للحضانة ترتيب علاج طبي طارئ إذا تعذّر الوصول إليّ",
    "c.birthday_wall": "إظهار الاسم الأول لطفلي وأول حرف من اسم العائلة وعمره على لوحة أعياد الميلاد في الموقع",
    yes: "نعم", no: "لا",
    docs_intro: "يُرجى رفع صورة أو مسح ضوئي واضح (JPG أو PNG أو WebP أو HEIC أو PDF، بحد أقصى ٥ ميجابايت لكل ملف). يمكنك أيضاً إرسالها لاحقاً: سنخبرك إن كان هناك نقص.",
    doc_birth: "شهادة الميلاد", doc_vacc: "سجل التطعيمات", doc_other: "مستند آخر (اختياري)", doc_add: "إضافة ملف", uploading: "جارٍ الرفع…", uploaded: "تم الرفع", doc_remove: "حذف",
    upload_failed: "تعذّر رفع هذا الملف. يُرجى المحاولة مرة أخرى.", bad_type: "يُرجى اختيار صورة (JPG أو PNG أو WebP أو HEIC) أو ملف PDF.", too_big: "حجم هذا الملف أكبر من ٥ ميجابايت. يُرجى اختيار ملف أصغر.",
    rate: "عدد الملفات كبير. يُرجى المحاولة بعد قليل.",
    review_intro: "يُرجى مراجعة كل شيء. يمكنك الرجوع لتعديل أي إجابة.", review_none: "لم يُذكر شيء",
    confirm: "أقرّ بأن المعلومات صحيحة، وقد قرأت", privacy: "إشعار الخصوصية",
    need_confirm: "يُرجى وضع علامة للتأكيد.",
    trap_label: "اتركه فارغاً",
    done_title: "شكراً لك! لقد استلمنا طلبك", done_no: "رقم طلبك هو", done_email: "أرسلنا رسالة تأكيد إلى",
    done_next: "ما يحدث بعد ذلك: يراجع فريقنا طلبك ويتواصل معك. إذا احتجنا إلى شيء إضافي أو لترتيب زيارة سنتواصل معك. إذا قُبل طفلك فستصلك رسالة بريد إلكتروني برابط لإعداد حسابك في بوابة أولياء الأمور.",
    done_call: "لديك أسئلة؟ اتصل بنا على 01063344389 (من الأحد إلى الخميس، من ٨ صباحاً إلى ٦ مساءً).", done_home: "العودة إلى الموقع",
    err_generic: "حدث خطأ ما. يُرجى التحقق من اتصالك والمحاولة مرة أخرى.", err_dup: "لدينا بالفعل طلب لهذا الطفل من عنوان البريد الإلكتروني نفسه. إذا أردت تغيير شيء فيُرجى التواصل مع الحضانة.",
    err_rate: "استلمنا عدة طلبات منك بالفعل. يُرجى المحاولة لاحقاً أو التواصل مع الحضانة.", err_fast: "يُرجى مراجعة إجاباتك لحظة، ثم اضغط إرسال مرة أخرى.", err_missing: "لم يصل أحد الملفات التي رفعتها. يُرجى الرجوع إلى خطوة المستندات ورفعه مرة أخرى.",
    off: "التسجيل عبر الإنترنت غير متاح بعد. يُرجى استخدام نموذج الاستفسار السريع في موقعنا أو الاتصال على 01063344389.", noscript: "يُرجى تفعيل JavaScript لاستخدام نموذج التسجيل.",
    bad_phone: "يُرجى إدخال رقم هاتف صحيح.", bad_email: "يُرجى إدخال بريد إلكتروني صحيح.", bad_date: "يُرجى التحقق من التاريخ.",
  },
};
